# Generated by Django 5.1.4 on 2025-01-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
