# Generated by Django 5.1.4 on 2025-01-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_description_course_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(),
        ),
    ]
