# Generated by Django 5.1.4 on 2025-01-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_content_alter_course_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
